public class Tester {
  
  public static void main(String[] args) {
    String message = "COC PZ KHP HLR AYS DVRPROVECUBC AYS BEDPULRTPS.“ZRNEXHXO,” EWL SOJ HHZD ED OZM LH AYEJ RSZMMTK KHP QHEK QGVD WSTYV TST ZBIQU DRS SPBCEO JW. “ZCZJSU GZ LPKH JDB RGLXU. NE’GT TRDP HVDE XDUVY.”EWL FLO BHE HLS ARURWA KHP QVP TZ UPJH LCK KHP QVP LZKLU HTB.“UF,” TST VCD XPU JATS. “FFU’CT DZTS P SLCVN IFAE. HARY HXAY TSTT.”“SUE GLDEXQLI HZL FFU HTUK ETVOKY-DTCVN OPFJ WTIOFUE UPJH LCK KHPC DV CLJNYT MXN FNPHLMECN KRY QDY KHCTL NEPZZ.”“Z RPBLDBPG,” AYE ZAK DAY HHZD. “T ZUFW JDB UIO CVK LPPCV MP QLTAFHL POF SVLBETK.”“ZT HPZ GAAP TRDP BL CELKL. Z AX P IFY LCK Z MFHA FBPN OZM.”“T ZUFW,” EWL FLO BHE SLXK. “ZT TH XLIET UFRXPS.”“YE SPZE’T XJJY FLXAY.”[10] “NZ,” IOV OWS TRN DPPU. “BFI DV HLKL. YAGTU’K WP?”‘NLJ,” TST IFY DPPU. “CLC P FFQTY POF P IVEC DU KHP ILIRLRL RNO IOVN HT’SC TLZL KHP HALFQ WVDE.”“HWF EOE?” IOV OWS TRN DPPU. “BPIDVEY UPJHPGTVN.”EWLP SLI VE TST AVRCPJV AYS TRNJ DM KHP UPJHPGTVN XPKV FFC VW TST VCD XPU RNO WL NAD CVKAYVYP. OEWLIS, ZU AYE ZAKVR QXZYECBLE, LZDRVD LI OZM LCK NECT ZRD. MJA KHPN KZD YDA JHZL PK AYS AYEJHWFKP EVCIETSP AMDBK TST JLRCTUK AYS AYE OTWKHD IOVY SPK URTUAVD EWLZR WXUVS LI HED EWL JTPPKP GZDKNELIOVR LCK FF HWHK TSTF YAO HLVN. EWL JUNRLJSQJS WIDWLIMPC VW TSPA UAJ LLIE LAYVAON PE AYS ORDMJATHPGLU TSTPI MLGSZN ZJA RNO RHIRTTK KHPB SRIO UBCL WTUXTS PJIODH ANO AAHEKD, LPKH ELV DEY";
    Message M1 = new Message(message);
    M1.vigenereAnalysis();
  }
}
